name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: create_release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true

  release_assets:
    needs: create_release
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Swatinem/rust-cache@v1

      - name: "add rustup wasm targets"
        run: |
          rustup target add wasm32-wasi
          rustup target add wasm32-unknown-unknown    
      
      - run : choco install openssl
        if: ${{ fromJSON(matrix.config.os == 'windows-latest') }}

      - run : brew install openssl
        if: ${{ fromJSON(matrix.config.os == 'macos-latest') }}

      - name: "build for unix"
        run: make build
        if: ${{ fromJSON(matrix.config.os == 'ubuntu-latest') }}

      - name: "build for windows"
        run: make build
        if: ${{ fromJSON(matrix.config.os == 'windows-latest') }}
        env:
          OPENSSL_DIR: C:\Program Files\OpenSSL-Win64\

      - name: "build for macos"
        run: make build
        if: ${{ fromJSON(matrix.config.os == 'macos-latest') }}
        env:
          OPENSSL_ROOT_DIR: /usr/local/opt/openssl          

      - run: make prepare-release
        if: ${{ fromJSON(matrix.config.os == 'ubuntu-latest') }}

      - run: make prepare-release-win
        if: ${{ fromJSON(matrix.config.os == 'windows-latest') }}

      - run: make prepare-release-mac
        if: ${{ fromJSON(matrix.config.os == 'macos-latest') }}        

      - name: "add wits, and slight-unix and templates tars to release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            slight-unix.tar.gz
            *-template.tar.gz
            wit/*.wit
        if: ${{ fromJSON(matrix.config.os == 'ubuntu-latest') }}

      - name: "add slight-win tar to release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            slight-win.tar.gz
        if: ${{ fromJSON(matrix.config.os == 'windows-latest') }}

      - name: "add slight-mac tar to release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            slight-mac.tar.gz
        if: ${{ fromJSON(matrix.config.os == 'macos-latest') }}            
            